from .create_achievement import (
    EXAMPLE_CREATE_ACHIEVEMENT_BODY,
    EXAMPLE_CREATE_ACHIEVEMENT_RESPONSE
)
from .get_achievements import EXAMPLE_GET_ACHIEVEMENTS_RESPONSE
from .get_user_info import EXAMPLE_GET_USER_INFO_RESPONSE

__all__ = (
    'EXAMPLE_GET_USER_INFO_RESPONSE',
    'EXAMPLE_CREATE_ACHIEVEMENT_BODY',
    'EXAMPLE_CREATE_ACHIEVEMENT_RESPONSE',
    'EXAMPLE_GET_ACHIEVEMENTS_RESPONSE',
)
